name: "Dependent Jobs"
on: [push]
jobs:
  First_Job:
    runs-on: self-hosted
    steps:
      - name: "First Job tasks"
        run: |
          echo "First Job is done"
  
  Second_Job:
    runs-on: self-hosted
    needs: First_Job
    steps:
      - name: "Second Job tasks"
        run: |
          echo "Second Job is done"
  

  Third_Job:
    runs-on: ubuntu-latest
    needs: [First_Job, Second_Job,Sixth_Job]
    steps:
      - name: "Third Job tasks"
        run: |
          echo "Third Job is done"
  
  Fourth_Job:
    runs-on: ubuntu-latest
    needs: [Third_Job]
    steps:
      - name: "Fourth Job tasks"
        run: |
          echo "Fourth Job is done"
  
  Fifth_Job:
    runs-on: ubuntu-latest
    needs: Second_Job
    steps:
      - name: "Fifth Job tasks"
        run: |
          echo "Fifth Job is done"

  Sixth_Job:
    runs-on: self-hosted
    steps:
      - name: "Sixth Job tasks"
        run: |
          echo "Sixth Job is done"
  

  
