name: Artifact and Output Example

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test1 }}
      output2: ${{ steps.step1.outputs.test2 }}

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Create a file
      run: echo "This is a file for artifact testing" > artifact.txt

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: my-artifact
        path: artifact.txt

    - name: Set output
      id: step1
      run: |
        echo "::set-output name=test1::hello-world"
        echo "test2=hello-world-baby" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@main
      with:
        name: my-artifact

    - name: Display structure of downloaded files
      run: ls -R

    - name: Use output from previous job
      run: |
        echo "The output from job1 is ${{ needs.job1.outputs.output1 }}"
        echo "The output from job1 is ${{ needs.job1.outputs.test2 }}"