name: Artifact and Output Example

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      test2: ${{steps.step1.outputs.test2}}
      fun: "crazy"

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Create a file1
      run: echo "This is a file for artifact testing" > artifact.txt

    
    - name: Create a file2
      run: echo "Yellow yellow dirty fellow" > artifact2.txt

    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: my-artifact
        path: |
          artifact.txt
          artifact2.txt

    - name: Set output
      id: step1
      run: |
        echo "test2=hello-world-baby" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@main
      with:
        name: my-artifact

    - name: Display structure of downloaded files
      run: ls -R
    
    - name: Contenets in the file
      run: |
        cat artifact.txt
        cat artifact2.txt

    - name: Use output from previous job
      run: |
        echo "The output from job1 is ${{ needs.job1.outputs.test2}}"
        echo "The output from job1 is ${{ needs.job1.outputs.fun}}"