name: "Custom_Multiple_Action_Test"

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Uses my custom function
      uses: sumith97/custom-action@v1.0.0
      id: custom
      with:
        who-to-greet: 'Mona the Octocats'
    - name: Get the output time check
      run: |
        echo "The time was ${{ steps.custom.outputs.time }}"
        echo "${{ steps.custom.outputs.fun }} common man"
        echo "Man I love you !!!!"
        echo "funny fellow2 !!!!"