name: "Custom_Action_Test"

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Uses my custom function
      uses: sumith97/custom-action@main
      id: custom
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Get the output time check
      run: |
        echo "The time was ${{ steps.custom.outputs.time }}"
        echo "Man I love you !!!!"