name: Custom_Action

on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world action step
      uses: sumith97/custom-action@main
      id: hello
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"