name: Expression Functions Demo

on:
  push:
    branches:
      - main
  issues:
    types: [opened, labeled]

jobs:
  expression-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Check if string contains substring
        if: contains('Hello world', 'llo')
        run: echo "The string contains the substring."