name: sheduling jobs in Github
on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  hello_world:
    runs-on: self-hosted
    steps:
      - name: Echo current time
        run: echo "The current server time is $(date)"
