name: parctise
on: [push]

jobs:
  First:
    runs-on: ubuntu-latest
    steps:
      - name: checking
        run: echo "You are checking !!!!!"
      
      - run: echo "funny"
      - run: |
          echo "hello Bro !!!!"
          echo "Bumper !!!!"
  
  Second:
    runs-on: windows-latest
    needs: First
    steps:
      - name: Doing
        run: echo "Bloody hell"
      
      - run: |
          echo "This is a windows job"
