name: context_demo
on: [push]

jobs:
  case1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ['${{github.repository}}' == 'sumith97/Github-Examples']; then
            echo "This repository is ${{github.repository}}"
          fi
          if [ "$GITHUB_REPOSITORY" == 'sumith97/Github-Examples']; then
            echo "This repository is ${{github.repository}}"
          fi
        continue-on-error: true
