name: parctise
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  First:
    runs-on: ubuntu-latest
    steps:
      - name: checking
        run: echo "You are checking !!!!!"
      
      - run: echo "funny"
      - run: |
          echo "hello Bro !!!!"
          echo "Bumper !!!!"
  
  Second:
    runs-on: windows-latest
    needs: First
    steps:
      - name: Doing
        run: echo "Bloody hell"
      
      - run: |
          echo "This is a windows job"
  
  Third:
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest,windows-latest]
        ver: [1,2,3,4,8,9]
        include:
          - ver: 5
            os: ubuntu-latest
        exclude:
          - {os: windows-latest, ver: 2}
          - {os: windows-latest, ver: 3}

    runs-on: ${{matrix.os}}
    steps:
      - run: echo "This is from ${{matrix.os}} and ${{matrix.ver}}machine"
