name: context_demo
on: [push]

jobs:
  case1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "${{ github.repository }}" = "sumith97/Github-Examples" ]; then
            echo "This repository is ${{github.repository}}"
            exit 1
          fi
          if [ "$GITHUB_REPOSITORY" == "sumith97/Github-Examples" ]; then
            echo "This repository is $GITHUB_REPOSITORY environment variable"
          fi
      - run: |
          echo "Check if it works"  

  # case2:
  #   runs-on: ubuntu-latest
  #   needs: case1
  #   if: needs.case1.result == 'failure' || always()
  #   steps:
  #     - run: echo "funny fellow!!!!"
  #     - run: echo "case1 result :${{needs.case1.result}}"

  case2:
    runs-on: ubuntu-latest
    if: needs.case1.result == 'failure' || always()
    needs: case1
    steps:
      - name: Log Group
        run: |
          echo ::group::Case2 Logs
          echo "case1 result: ${{ needs.case1.result }}"
          echo "case2 is running because case1 failed"
          echo ::debug::Debug message from case2
          echo ::warning::Warning message from case2
          echo ::error::Error message from case2
          echo ::endgroup::
