name: Webhook Event Handler

on:
  repository_dispatch:
    types:
      - webhook_fun

jobs:
  process-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log Event Information
        run: |
          echo "Event type: $GITHUB_EVENT_NAME"
          echo "This is crazy !!!!!"